{% set version = '0.7.6' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-vcfppr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vcfppR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vcfppR/vcfppR_{{ version }}.tar.gz
  sha256: 097a35773c044199e036a5ea42c418153f5360f9bf83db0a5e111a92d8477844

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - r-rcpp

test:
  commands:
    - $R -e "library('vcfppR')"           # [not win]
    - "\"%R%\" -e \"library('vcfppR')\""  # [win]

about:
  home: https://github.com/Zilong-Li/vcfppR
  license: MIT
  summary: The 'vcfpp.h' (<https://github.com/Zilong-Li/vcfpp>) provides an easy-to-use 'C++'
    'API' of 'htslib', offering full functionality for manipulating Variant Call Format
    (VCF) files. The 'vcfppR' package serves as the R bindings of the 'vcfpp.h' library,
    enabling rapid processing of both compressed and uncompressed VCF files. Explore
    a range of powerful features for efficient VCF data manipulation.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - Zilong-Li

# Package: vcfppR
# Title: Rapid Manipulation of the Variant Call Format (VCF)
# Version: 0.7.6
# Authors@R: c( person("Zilong", "Li", , "zilong.dk@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-5859-2078")), person("Bonfield, James K and Marshall, John and Danecek, Petr and Li, Heng and Ohan, Valeriu and Whitwham, Andrew and Keane, Thomas and Davies, Robert M",  role = "cph", comment = "Authors of included htslib library") )
# Copyright: See the file COPYRIGHTS for various htslib copyright details
# Description: The 'vcfpp.h' (<https://github.com/Zilong-Li/vcfpp>) provides an easy-to-use 'C++' 'API' of 'htslib', offering full functionality for manipulating Variant Call Format (VCF) files. The 'vcfppR' package serves as the R bindings of the 'vcfpp.h' library, enabling rapid processing of both compressed and uncompressed VCF files. Explore a range of powerful features for efficient VCF data manipulation.
# Encoding: UTF-8
# Depends: R (>= 3.6.0)
# RoxygenNote: 7.3.2
# Suggests: knitr, codetools, rmarkdown, testthat (>= 3.0.0)
# Config/testthat/edition: 3
# SystemRequirements: libcurl: libcurl-devel (rpm) or libcurl4-openssl-dev (deb), GNU make.
# Imports: Rcpp, methods, stats, utils
# LinkingTo: Rcpp
# URL: https://github.com/Zilong-Li/vcfppR
# BugReports: https://github.com/Zilong-Li/vcfppR/issues
# License: MIT + file LICENSE
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2025-03-31 07:50:49 UTC; zilong
# Author: Zilong Li [aut, cre] (<https://orcid.org/0000-0001-5859-2078>), Bonfield, James K and Marshall, John and Danecek, Petr and Li, Heng and Ohan, Valeriu and Whitwham, Andrew and Keane, Thomas and Davies, Robert M [cph] (Authors of included htslib library)
# Maintainer: Zilong Li <zilong.dk@gmail.com>
# Repository: CRAN
# Date/Publication: 2025-03-31 08:10:02 UTC
